import { FormArray, FormBuilder, FormGroup, Validators } from '@angular/forms';

export class PrecioProdListComponent {
  public listOfID = [
    { id: 'input-general-s-1', step: 1, user: 'general' },
    { id: 'input-general-e-1', step: 1, user: 'general' },
    { id: 'input-general-p-1', step: 1, user: 'general' },
    { id: 'input-general-d-1', step: 1, user: 'general' },
    { id: 'input-general-s-2', step: 2, user: 'general' },
    { id: 'input-general-e-2', step: 2, user: 'general' },
    { id: 'input-general-p-2', step: 2, user: 'general' },
    { id: 'input-general-d-2', step: 2, user: 'general' },
    { id: 'input-general-s-3', step: 3, user: 'general' },
    { id: 'input-general-e-3', step: 3, user: 'general' },
    { id: 'input-general-p-3', step: 3, user: 'general' },
    { id: 'input-general-d-3', step: 3, user: 'general' },
    { id: 'input-general-s-4', step: 4, user: 'general' },
    { id: 'input-general-e-4', step: 4, user: 'general' },
    { id: 'input-general-p-4', step: 4, user: 'general' },
    { id: 'input-general-d-4', step: 4, user: 'general' },
    { id: 'input-general-s-5', step: 5, user: 'general' },
    { id: 'input-general-e-5', step: 5, user: 'general' },
    { id: 'input-general-p-5', step: 5, user: 'general' },
    { id: 'input-general-d-5', step: 5, user: 'general' },

    { id: 'input-1-s-1', step: 1, user: 'seller-1' },
    { id: 'input-1-e-1', step: 1, user: 'seller-1' },
    { id: 'input-1-p-1', step: 1, user: 'seller-1' },
    { id: 'input-1-d-1', step: 1, user: 'seller-1' },
    { id: 'input-1-s-2', step: 2, user: 'seller-1' },
    { id: 'input-1-e-2', step: 2, user: 'seller-1' },
    { id: 'input-1-p-2', step: 2, user: 'seller-1' },
    { id: 'input-1-d-2', step: 2, user: 'seller-1' },
    { id: 'input-1-s-3', step: 3, user: 'seller-1' },
    { id: 'input-1-e-3', step: 3, user: 'seller-1' },
    { id: 'input-1-p-3', step: 3, user: 'seller-1' },
    { id: 'input-1-d-3', step: 3, user: 'seller-1' },
    { id: 'input-1-s-4', step: 4, user: 'seller-1' },
    { id: 'input-1-e-4', step: 4, user: 'seller-1' },
    { id: 'input-1-p-4', step: 4, user: 'seller-1' },
    { id: 'input-1-d-4', step: 4, user: 'seller-1' },
    { id: 'input-1-s-5', step: 5, user: 'seller-1' },
    { id: 'input-1-e-5', step: 5, user: 'seller-1' },
    { id: 'input-1-p-5', step: 5, user: 'seller-1' },
    { id: 'input-1-d-5', step: 5, user: 'seller-1' },

    { id: 'input-2-s-1', step: 1, user: 'seller-2' },
    { id: 'input-2-e-1', step: 1, user: 'seller-2' },
    { id: 'input-2-p-1', step: 1, user: 'seller-2' },
    { id: 'input-2-d-1', step: 1, user: 'seller-2' },
    { id: 'input-2-s-2', step: 2, user: 'seller-2' },
    { id: 'input-2-e-2', step: 2, user: 'seller-2' },
    { id: 'input-2-p-2', step: 2, user: 'seller-2' },
    { id: 'input-2-d-2', step: 2, user: 'seller-2' },
    { id: 'input-2-s-3', step: 3, user: 'seller-2' },
    { id: 'input-2-e-3', step: 3, user: 'seller-2' },
    { id: 'input-2-p-3', step: 3, user: 'seller-2' },
    { id: 'input-2-d-3', step: 3, user: 'seller-2' },
    { id: 'input-2-s-4', step: 4, user: 'seller-2' },
    { id: 'input-2-e-4', step: 4, user: 'seller-2' },
    { id: 'input-2-p-4', step: 4, user: 'seller-2' },
    { id: 'input-2-d-4', step: 4, user: 'seller-2' },
    { id: 'input-2-s-5', step: 5, user: 'seller-2' },
    { id: 'input-2-e-5', step: 5, user: 'seller-2' },
    { id: 'input-2-p-5', step: 5, user: 'seller-2' },
    { id: 'input-2-d-5', step: 5, user: 'seller-2' },

    { id: 'input-3-s-1', step: 1, user: 'seller-3' },
    { id: 'input-3-e-1', step: 1, user: 'seller-3' },
    { id: 'input-3-p-1', step: 1, user: 'seller-3' },
    { id: 'input-3-d-1', step: 1, user: 'seller-3' },
    { id: 'input-3-s-2', step: 2, user: 'seller-3' },
    { id: 'input-3-e-2', step: 2, user: 'seller-3' },
    { id: 'input-3-p-2', step: 2, user: 'seller-3' },
    { id: 'input-3-d-2', step: 2, user: 'seller-3' },
    { id: 'input-3-s-3', step: 3, user: 'seller-3' },
    { id: 'input-3-e-3', step: 3, user: 'seller-3' },
    { id: 'input-3-p-3', step: 3, user: 'seller-3' },
    { id: 'input-3-d-3', step: 3, user: 'seller-3' },
    { id: 'input-3-s-4', step: 4, user: 'seller-3' },
    { id: 'input-3-e-4', step: 4, user: 'seller-3' },
    { id: 'input-3-p-4', step: 4, user: 'seller-3' },
    { id: 'input-3-d-4', step: 4, user: 'seller-3' },
    { id: 'input-3-s-5', step: 5, user: 'seller-3' },
    { id: 'input-3-e-5', step: 5, user: 'seller-3' },
    { id: 'input-3-p-5', step: 5, user: 'seller-3' },
    { id: 'input-3-d-5', step: 5, user: 'seller-3' },

    { id: 'input-4-s-1', step: 1, user: 'seller-4' },
    { id: 'input-4-e-1', step: 1, user: 'seller-4' },
    { id: 'input-4-p-1', step: 1, user: 'seller-4' },
    { id: 'input-4-d-1', step: 1, user: 'seller-4' },
    { id: 'input-4-s-2', step: 2, user: 'seller-4' },
    { id: 'input-4-e-2', step: 2, user: 'seller-4' },
    { id: 'input-4-p-2', step: 2, user: 'seller-4' },
    { id: 'input-4-d-2', step: 2, user: 'seller-4' },
    { id: 'input-4-s-3', step: 3, user: 'seller-4' },
    { id: 'input-4-e-3', step: 3, user: 'seller-4' },
    { id: 'input-4-p-3', step: 3, user: 'seller-4' },
    { id: 'input-4-d-3', step: 3, user: 'seller-4' },
    { id: 'input-4-s-4', step: 4, user: 'seller-4' },
    { id: 'input-4-e-4', step: 4, user: 'seller-4' },
    { id: 'input-4-p-4', step: 4, user: 'seller-4' },
    { id: 'input-4-d-4', step: 4, user: 'seller-4' },
    { id: 'input-4-s-5', step: 5, user: 'seller-4' },
    { id: 'input-4-e-5', step: 5, user: 'seller-4' },
    { id: 'input-4-p-5', step: 5, user: 'seller-4' },
    { id: 'input-4-d-5', step: 5, user: 'seller-4' },

    { id: 'input-5-s-1', step: 1, user: 'seller-5' },
    { id: 'input-5-e-1', step: 1, user: 'seller-5' },
    { id: 'input-5-p-1', step: 1, user: 'seller-5' },
    { id: 'input-5-d-1', step: 1, user: 'seller-5' },
    { id: 'input-5-s-2', step: 2, user: 'seller-5' },
    { id: 'input-5-e-2', step: 2, user: 'seller-5' },
    { id: 'input-5-p-2', step: 2, user: 'seller-5' },
    { id: 'input-5-d-2', step: 2, user: 'seller-5' },
    { id: 'input-5-s-3', step: 3, user: 'seller-5' },
    { id: 'input-5-e-3', step: 3, user: 'seller-5' },
    { id: 'input-5-p-3', step: 3, user: 'seller-5' },
    { id: 'input-5-d-3', step: 3, user: 'seller-5' },
    { id: 'input-5-s-4', step: 4, user: 'seller-5' },
    { id: 'input-5-e-4', step: 4, user: 'seller-5' },
    { id: 'input-5-p-4', step: 4, user: 'seller-5' },
    { id: 'input-5-d-4', step: 4, user: 'seller-5' },
    { id: 'input-5-s-5', step: 5, user: 'seller-5' },
    { id: 'input-5-e-5', step: 5, user: 'seller-5' },
    { id: 'input-5-p-5', step: 5, user: 'seller-5' },
    { id: 'input-5-d-5', step: 5, user: 'seller-5' },
  ];
  constructor() {}

  listOfIDs() {
    return this.listOfID;
  }
}
